baseURL: http://example.com/
languageCode: en-us
title: "Blogrolling"
theme: paperesque
copyright: © 2024 Jay Lee
buildDrafts: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      pygmentsUseClasses: yes
      unsafe: yes
params:
  topmenu:
    - name: Posts
      url: posts/
    - name: About
      url: about/
    - name: Subscribe
      url: subscribe/
